spring.application.name=emt2026

spring.datasource.url=jdbc:postgresql://localhost:5433/accommodation_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration